[build]
builder = "nixpacks"
buildCommand = "npm run build"
nixpacksConfigPath = "nixpacks.toml"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/api/stats"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
